// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'domain': string;
  'icon': string;
  'icon-clock': string;
  'icon-comments': string;
  'icon-user': string;
  'info-column': string;
  'item': string;
  'link': string;
  'loading-placeholder': string;
  'main-row': string;
  'meta': string;
  'narrow': string;
  'placeHolderShimmer': string;
  'rank': string;
  'score': string;
  'title': string;
  'wide': string;
}
declare var cssExports: CssExports;
export = cssExports;
