// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'domain': string;
  'item': string;
  'mainRow': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
