// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'dropdown': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
