// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'brand': string;
  'iconElem': string;
  'navbar': string;
  'pulse': string;
  'reloadIcon': string;
  'spacer': string;
  'withIndicator': string;
}
declare var cssExports: CssExports;
export = cssExports;
