// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'loader': string;
  'loading': string;
}
declare var cssExports: CssExports;
export = cssExports;
